#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "nDLQJ/ZPRNz5"
#define LAYER_STATE_16BIT

#define WHEEL_EXTENDED_SUPPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 1
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define MOUSE_EXTENDED_REPORT
#define NAVIGATOR_TRACKBALL_CPI 20
#define NAVIGATOR_SCROLL_DIVIDER 50 

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 7
#define AUTO_MOUSE_THRESHOLD 10
#define AUTO_MOUSE_SCROLL_THRESHOLD AUTO_MOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60





#undef VENDOR_ID
#undef PRODUCT_ID

#define VENDOR_ID       0x046A
#define PRODUCT_ID      0x00A1
